eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8097/eureka
   
   
spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/reservation_db
  username: ms_user
  password:	12345
  driver-class-name: org.postgresql.Driver
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect  